--------------------------------------------------------
--  DDL for Table FEE
--------------------------------------------------------

  CREATE TABLE "IMS"."FEE" 
   (	"FEECAT" NUMBER(2,0), 
	"ADMISSIONFEE" NUMBER(5,0), 
	"GAMEFEE" NUMBER(5,0), 
	"EXAMFEE" NUMBER(5,0), 
	"ABEYAANTRIXFEE" NUMBER(5,0), 
	"LABORATORYFEE" NUMBER(5,0), 
	"LIBRARYFEE" NUMBER(5,0), 
	"COMMONROOMFEE" NUMBER(5,0), 
	"TRANSPORTFEE" NUMBER(5,0), 
	"ELECTRICITYFEE" NUMBER(5,0), 
	"DEVELOPMENTFEE" NUMBER(5,0), 
	"COURSEID" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
