--------------------------------------------------------
--  DDL for Table OFFICE_STAFF
--------------------------------------------------------

  CREATE TABLE "IMS"."OFFICE_STAFF" 
   (	"STAFFID" VARCHAR2(20 BYTE), 
	"PID" NUMBER(20,0), 
	"DESIGNATION" VARCHAR2(30 BYTE), 
	"SALARY" NUMBER(10,0), 
	"QUALIFICATION" VARCHAR2(30 BYTE), 
	"PREVIOUS_WORK_EXP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
