--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "IMS"."PERSON" 
   (	"PID" NUMBER(20,0), 
	"DOA" DATE, 
	"FNAME" VARCHAR2(30 BYTE), 
	"MNAME" VARCHAR2(30 BYTE), 
	"LNAME" VARCHAR2(30 BYTE), 
	"FFNAME" VARCHAR2(30 BYTE), 
	"FMNAME" VARCHAR2(30 BYTE), 
	"FLNAME" VARCHAR2(30 BYTE), 
	"MFNAME" VARCHAR2(30 BYTE), 
	"MMNAME" VARCHAR2(30 BYTE), 
	"MLNAME" VARCHAR2(30 BYTE), 
	"NATIONALITY" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"DISTRICT" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(8,0), 
	"POSTOFFICE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE), 
	"LOCALITY" VARCHAR2(30 BYTE), 
	"PHONENO" NUMBER(10,0), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"DOB" DATE, 
	"BG" VARCHAR2(10 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"RELIGON" VARCHAR2(20 BYTE), 
	"CASTE" VARCHAR2(30 BYTE), 
	"PHOTOGRAPH" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTOGRAPH") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
