--------------------------------------------------------
--  DDL for Table STUDENT_FEE
--------------------------------------------------------

  CREATE TABLE "IMS"."STUDENT_FEE" 
   (	"FEECAT" NUMBER(2,0), 
	"STUID" VARCHAR2(20 BYTE), 
	"SUB" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
