--------------------------------------------------------
--  Constraints for Table FEE
--------------------------------------------------------

  ALTER TABLE "IMS"."FEE" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" ADD CONSTRAINT "FEE_PK" PRIMARY KEY ("FEECAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."FEE" MODIFY ("DEVELOPMENTFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("ELECTRICITYFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("TRANSPORTFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("COMMONROOMFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("LIBRARYFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("LABORATORYFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("ABEYAANTRIXFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("EXAMFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("GAMEFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("ADMISSIONFEE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."FEE" MODIFY ("FEECAT" NOT NULL ENABLE);
