--------------------------------------------------------
--  Constraints for Table OFFICE_STAFF
--------------------------------------------------------

  ALTER TABLE "IMS"."OFFICE_STAFF" ADD CONSTRAINT "OFFICE_STAFF_PK" PRIMARY KEY ("STAFFID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."OFFICE_STAFF" MODIFY ("QUALIFICATION" NOT NULL ENABLE);
  ALTER TABLE "IMS"."OFFICE_STAFF" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "IMS"."OFFICE_STAFF" MODIFY ("DESIGNATION" NOT NULL ENABLE);
  ALTER TABLE "IMS"."OFFICE_STAFF" MODIFY ("PID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."OFFICE_STAFF" MODIFY ("STAFFID" NOT NULL ENABLE);
