--------------------------------------------------------
--  Constraints for Table SEMESTER
--------------------------------------------------------

  ALTER TABLE "IMS"."SEMESTER" ADD CONSTRAINT "SEMESTER_PK" PRIMARY KEY ("SUB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."SEMESTER" MODIFY ("SUB" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SEMESTER" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SEMESTER" MODIFY ("SEMNO" NOT NULL ENABLE);
