--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "IMS"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "IMS"."STUDENT" MODIFY ("CURRENTSTATUS" NOT NULL ENABLE);
  ALTER TABLE "IMS"."STUDENT" MODIFY ("BATCHNO" NOT NULL ENABLE);
  ALTER TABLE "IMS"."STUDENT" MODIFY ("DEPTID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."STUDENT" MODIFY ("PID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."STUDENT" MODIFY ("STUID" NOT NULL ENABLE);
