--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "IMS"."SUBJECT" MODIFY ("SUB" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SUBJECT" MODIFY ("PAPERCODE" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SUBJECT" MODIFY ("PAPERNAME" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SUBJECT" MODIFY ("PAPERID" NOT NULL ENABLE);
  ALTER TABLE "IMS"."SUBJECT" ADD CONSTRAINT "SUBJECT_PK" PRIMARY KEY ("PAPERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
