--------------------------------------------------------
--  File created - Tuesday-July-11-2017   
--------------------------------------------------------
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DROPS\DROP.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\ADMIN.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\ATTENDANCE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\COURSE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\DEPARTMENT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\EXAM.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\EXAM_SUB.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\FEE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\LASTLOGIN.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\OFFICE_STAFF.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\PERSON.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\SEMESTER.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\STUDENT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\STUDENT_COURSE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\STUDENT_FEE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\SUBJECT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TABLES\TEACHING_STAFF.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\DEMO_CUST_SEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\DEMO_ORDER_ITEMS_SEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\DEMO_ORD_SEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\DEMO_PROD_SEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\DEMO_USERS_SEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\EXAMSEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\NONTEACHERSEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\PERSONSEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\STUDENTSEQ.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\SEQUENCES\TEACHERSEQ.sql
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\ADMIN.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\ATTENDANCE.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\COURSE.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\DEPARTMENT.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\EXAM.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\EXAM_SUB.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\FEE.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\LASTLOGIN.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\OFFICE_STAFF.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\PERSON.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\SEMESTER.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\STUDENT.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\STUDENT_COURSE.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\STUDENT_FEE.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\SUBJECT.xlsx
--@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\DATA_TABLE\TEACHING_STAFF.xlsx
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\FEE_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\DEPARTMENT_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\EXAM_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\PERSON_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\COURSE_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\SUBJECT_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\TEACHING_STUFF_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\EMAILID_ALREADY_EXISTED.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\STUDENT_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\ADMIN_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\OFFICE_STAFF_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\INDEXES\SEMESTER_PK.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TRIGGERS\EXAM_TRG.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TRIGGERS\PERSON_TRG.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\TRIGGERS\STUDENT_TRG.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\FUNCTIONS\CUSTOM_AUTH.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\FUNCTIONS\CUSTOM_HASH.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\SEMESTER.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\ADMIN.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\STUDENT_COURSE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\OFFICE_STAFF.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\COURSE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\SUBJECT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\EXAM_SUB.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\TEACHING_STAFF.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\EXAM.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\STUDENT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\STUDENT_FEE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\PERSON.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\DEPARTMENT.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\FEE.sql
@C:\Users\End User\Documents\program\DBMS\ORACLE\4th Sem Minor Project\Database\Database 10\CONSTRAINTS\ATTENDANCE.sql
